name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -halt-on-error -shell-escape
      - name: makeindex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.nlo
          compiler: makeindex
          args: -s nomencl.ist -o main.nls
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.aux
          compiler: bibtex
          args: 
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -halt-on-error -shell-escape
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -halt-on-error -shell-escape